### ISSUE TITLE
validation list of 1811 release

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5780]
master ticket to keep track of what we need to test for this release. Let's edit the following task lists.

REST
- [x] wmcore 1.1.18
- [x] TAPERECALL tasks abandoned when TW changes name #5760
- [x] fix for the publication of directly staged files #5754 

TASK WORKER for PRODUCTION
- [x] create branch and align with master where proper #5779 
- [x] fix string formats in TapeRecall #5774
- [x] point to preDag log for AutomatSplit #5751 #5775
- [x] proper x509 env to talk to CRIC #5756 #5764 #5770 
- [x] Autom.Splitting preDag fails to import httplib2 #5752
- [x] False warning about blocks containing only invalid files #5762
- [x] Uses ASO server, not ASOLess 

TASK WORKER for ASOLESS
- [x] create branch and align with master where proper #5779 
- [x] use pycurl in ASOless to talk to PhEDEx from schedd #5777

**Comment by belforte** [comment]
at this moment we have 3.3.1811.rc7 where all has been tested but the thing which requires new REST since cmsweb-tested is currently broken for everybodym i.e.
-  fix for the publication of directly staged file
- TAPERECALL fixes
