### ISSUE TITLE
document all places where CRABCache is used

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6400]
document all places where CRABCache is used and describe the needed functionality

i.e. look for all places where there are references to
https://github.com/dmwm/CRABServer/tree/master/src/python/UserFileCache

**Comment by ddaina** [comment]
@belforte I had first look into this task and tried to list files that uses `UserFileCache`. I documented it in excel, once we get through review cycle and come to the final result, I will copy it here for documentation purpose.

For now, you can find file [here](https://docs.google.com/spreadsheets/d/1Wj8HUV_2xxLTQbaYs37LnOo1vH8zyNnjEGv7eZTXu50/edit?usp=sharing).

**Comment by belforte** [comment]
thanks, looks good. See also  https://github.com/dmwm/CRABClient/issues/4971

**Comment by belforte** [comment]
I am turning [that spreadsheet](https://docs.google.com/spreadsheets/d/1Wj8HUV_2xxLTQbaYs37LnOo1vH8zyNnjEGv7eZTXu50/edit?usp=sharing) into a list items below. I have also updated the spreadsheet with comments as appropriate.

Will mark tasks below as closed once they have their own GH issues so we close this as "done with making the list".

- [ ] use S3 for DryRun tarball uploading in TW/DryRunUploder.py ( #6465 ) and in `submit --dry` in client (**GH issue to be opened**)
- [ ] remove "sandbox touching" in tape recall recurring action when sandbox is in S3 ( #6466 )
- [ ] upload TW log to S3  ( #6459 )
- [ ] figure out that to do with  <https://github.com/dmwm/CRABServer/blob/master/setup.py> , look just a setup file
- [ ] remove references to crabcache in old, unused CRAB Client which refer to crabcache :  https://github.com/dmwm/CRABClient/blob/master/test/python/CRABClient_t/JobType_t/CMSSW_t.py and https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Emulator.py**. GH issue to be opened**.

**Comment by ddaina** [comment]
>  verify if there is references to crabcache in old, unused CRAB Client test file https://github.com/dmwm/CRABClient/blob/master/test/python/CRABClient_t/JobType_t/CMSSW_t.py and remove it

indeed, crabcache is not used there. we can mark it is `done`.

Also, I cannot find in this list issue that would cover this use case: https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L1157-#L1174

**Comment by belforte** [comment]
well spotted. I added a note [here]9https://github.com/dmwm/CRABServer/issues/6457#issuecomment-799753904)
