### ISSUE TITLE
Refactor and improve scripts to create and run containers

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6429]
Recap here a few scattered issues and PR' from last week so to put order and cleanup strategy.
Main points of breakdown from past are:
1. we have only one application version inside each container image
2. we want to make running and updating versions  as automated as possible while preserving and improving debugging capability
3. we want to get rid of old VM-based installation for development

**Therefore**:

* All container images (crabserver and  TaskWorker) will have a `run.sh` script which is called in the Dockerfile `CMD` line and is used "in production" to run the image (by K8s for crabserver, by our [runContainer.sh](https://github.com/dmwm/CRABServer/blob/master/src/script/Container/runContainer.sh) for TW and Publishers.
* The TaskWorker image can be used to run one of various services, currently we have TaskWorker, Publisher_schedd, Publisher_rucio, Publisher_asoless, but we can introduce more later if convenient
* All images will have a `start.sh` and a `stop.sh` to be used interactively for testing and debugging the services from a shell inside the container (either via `k8ctl -n crab exec -ti <pod> -- bash` or docker exec -ti <image-name> /bin/bash`
* All images will contain a `${GHrepoDir}` directory with clones of WMCore and CRABServer repositories where the same tag as used in building the image will checked out
* The `start.sh` script will have options to select running from GH repos and/or to run in debug mode.Calling it w/o option will make it fail and print help (differently from the past) and the behavior needed for automatic starting the container image

That plan was broken into following issues
- [x] an older writeup of this, whish lists most of items below but is less clear while will worth reading - #6416
- [x] introduce `run.sh` -  #6417
- [x] add options to `start.sh` to implement run from GH and/or run in debug mode #6418
- [x] deploy GH clones for CRABServer and WMCore inside the container - #6422
- [x] simplify and unify as much as possible `start.sh` and `env.sh` for TW and Publisher
- [x] overall harmonize, polish and document all  changes from above issues - #6428
- [x] add start.sh and stop.sh to crabserver - #6419 
- [x] make it possible to start crabserver container w/o startin the service  - #6420 (this is not really needed, low prio)
- [x] add debug option to crabserver start - #6436
   - [x] requires https://github.com/dmwm/WMCore/issues/10266
