### ISSUE TITLE
CRABServer REST should not talk to CRIC

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6917]
better to avoid talking to any external service from the REST
supporting proper authentication and debugging problems is too much of a pain
IIRC this access is only used to fill the site whitelist for MC with "all sites".
Which in principle can be done in TW.
I looked at this some time ago and change seemed too big to be worth.
But now I think that it is worth the effort.

**Comment by belforte** [comment]
current code in REST relies on https://github.com/dmwm/CRABServer/blob/2ed6f598b6ff5ca0812d9430aaadff40d5732101/src/python/CRABInterface/RESTUserWorkflow.py#L44 and https://github.com/dmwm/CRABServer/blob/2ed6f598b6ff5ca0812d9430aaadff40d5732101/src/python/CRABInterface/Utilities.py#L172-L176 to get list of sites from CRIC every 30min and cache in memory.
(By the way that's hard to understand since WMCore CRIC class already has a 1h default cache inside... oh well...)

TaskWorker actions are done in independente processes, so it woule make sense to reuse `_expandSites` but cache site list on a disk file instead (like we used to do with SiteDB info long time ago), list of sites from CRIC does not need to be refreshed any faster than once a day !! Anyhow.. since it is one call per task.. we may even do it every time, rate is low, is only a matter of riding outages. There should be two times set:
* when to refresh
* how long to use a stale cache
current caching reduces number of calls to external service, but makes things fail miserably if server is down when cache expires.
SHould definitely combine with the call to CRIC in DataDiscovery and have a single cache file, ref. https://github.com/dmwm/CRABServer/issues/6946

**Comment by belforte** [comment]
maybe a good topic for @mapellidario next month ? I am not comfortable with named ntuple and decorators (see https://github.com/dmwm/CRABServer/blob/2ed6f598b6ff5ca0812d9430aaadff40d5732101/src/python/CRABInterface/Utilities.py#L164)

**Comment by mapellidario** [comment]
I will need some guidance (as always), but I will happily take this!

**Comment by belforte** [comment]
thanks Dario. Certainly ! Let's assume that we can get to this sometimes in March

**Comment by sinonkt** [comment]
Regarding the #8937 changes
### Summary 
1. Now, ***CRIC***-related requests (calls) and site checking/expanding logic are handled by ***TaskWorker*** [1][2].
2. ***CRABServer*** no longer talk to ***CRIC***.
3. At ***TaskWorker***, we *minimize* ***CRIC***-related requests via file-based caching at `/tmp/tw-cache` and refreshing the cache **once per day** [3].

(See also test results [1][2][3])
___________
### Test Results
[1] When user submit *invalid site* (e.g.  ***T2_TH_Bangkok***) or glob pattern in either *whitelist* or *blacklist* to expand  (e.g. **T2_TH_\***).

***Instead*** of response right away to user with *CherryPy* ***400 Bad Request*** from **CRABServer** as following.
```
[kphornsi@lxplus905 workspace]$ ./submit.sh
Will use CRAB configuration file HC-1kj.T2_TH_Bangkok.py
Importing CMSSW configuration pset.py
Finished importing CMSSW configuration pset.py
...
HTTP code/reason = 400/Bad Request .  stdout:
...
        <h2>400 Bad Request</h2>
        <p>Invalid input parameter</p>
        <pre id="traceback"></pre>
...
The server answered with an error.
Server answered with: Invalid input parameter
Reason is: The parameter T2_TH_Bangkok is not in the list of known CMS Processing Site Names
Error Id: d85de5577b8e8ecfdcaef922cb54f18e
```
```
The server answered with an error.
Server answered with: Invalid input parameter
Reason is: Cannot expand site T2_TH_* to anything
Error Id: 114f34c56274730ced670100d7691d26
```
Now, It reject **Later** by ***TaskWorker*** with **SUBMITFAILED** task status as following. 
(PS. signified that *decommissioning* ***CRIC***-related functionalities on ***CRABServer*** works as expected)
```
[kphornsi@lxplus905 workspace]$ crab status -d /tmp/crabStatusTracking/crab_20250218_031815
Rucio client intialized for account kphornsi
CRAB project directory:		/tmp/crabStatusTracking/crab_20250218_031815
Task name:			250218_021818:kphornsi_crab_20250218_031815
Grid scheduler - Task Worker:	crab3@vocms059.cern.ch - crab-dev-tw03
Status on the CRAB server:	SUBMITFAILED
Task URL to use for HELP:	https://cmsweb-test12.cern.ch/crabserver/ui/task/250218_021818%3Akphornsi_crab_20250218_031815
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=kphornsi&var-task=250218_021818%3Akphornsi_crab_20250218_031815&from=1739841498000&to=now
Failure message from server:	A site name T2_TH_Bangkok that user specified is not in the list of known CMS Processing Site Names
Log file is /tmp/crabStatusTracking/crab_20250218_031815/crab.log
```
```
[kphornsi@lxplus905 workspace]$ crab status -d /tmp/crabStatusTracking/crab_20250218_033144
Rucio client intialized for account kphornsi
CRAB project directory:		/tmp/crabStatusTracking/crab_20250218_033144
Task name:			250218_023148:kphornsi_crab_20250218_033144
Grid scheduler - Task Worker:	crab3@vocms059.cern.ch - crab-dev-tw03
Status on the CRAB server:	SUBMITFAILED
Task URL to use for HELP:	https://cmsweb-test12.cern.ch/crabserver/ui/task/250218_023148%3Akphornsi_crab_20250218_033144
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=kphornsi&var-task=250218_023148%3Akphornsi_crab_20250218_033144&from=1739842308000&to=now
Failure message from server:	Remote output data site not valid, Cannot expand site T2_TH_* to anything
Log file is /tmp/crabStatusTracking/crab_20250218_033144/crab.log
```
[2] As well as, When user submit *banned* **Storage Site** regarding `banned-out-dest` from **external central config**.
(PS. implied that ***checkASODestination*** works as expected at ***TaskWorker***)
```
[kphornsi@lxplus905 workspace]$ crab status -d /tmp/crabStatusTracking/crab_20250218_050327
Rucio client intialized for account kphornsi
CRAB project directory:		/tmp/crabStatusTracking/crab_20250218_050327
Task name:			250218_040331:kphornsi_crab_20250218_050327
Grid scheduler - Task Worker:	crab3@vocms059.cern.ch - crab-dev-tw03
Status on the CRAB server:	SUBMITFAILED
Task URL to use for HELP:	https://cmsweb-test12.cern.ch/crabserver/ui/task/250218_040331%3Akphornsi_crab_20250218_050327
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=kphornsi&var-task=250218_040331%3Akphornsi_crab_20250218_050327&from=1739847811000&to=now
Failure message from server:	Remote output data site is banned, The output site you specified in the Site.storageSite parameter (T2_CH_CERN) is blacklisted (banned sites: ['T2_CH_CERN'])
Log file is /tmp/crabStatusTracking/crab_20250218_050327/crab.log
```
[3] Test output shows that ***CRIC*** requests have *not only* been  cached. 
```
crab3@crab-dev-tw03:/data/srv/current/lib/python/site-packages/TaskWorker$ CRIC_TTL=120 python3 ExternalService.py
===== Test::Begining with 3 cache keys and [354/18](hits/misses) =====
DEBUG:root:Fetching data from /api/cms/site/query/?json&preset=site-names, with args {'rcsite_state': 'ANY'}
DEBUG:root:getData:
	url: /api/cms/site/query/?json&preset=site-names&rcsite_state=ANY
	verb: GET
	incoming_headers: {}
	data: {}
DEBUG:root:Fetching data from /api/cms/site/query/?json&preset=site-names, with args {'rcsite_state': 'ANY'}
DEBUG:root:Data is from the Service cache
DEBUG:root:Fetching data from /api/cms/site/query/?json&preset=data-processing, with args {'rcsite_state': 'ANY'}
DEBUG:root:getData:
	url: /api/cms/site/query/?json&preset=data-processing&rcsite_state=ANY
	verb: GET
	incoming_headers: {}
	data: {}
===== Test::CacheKeys::[('__main__.CachedCRICService.getAllPSNs', None), ('__main__.CachedCRICService.PNNstoPSNs', [], None), ('__main__.CachedCRICService.getAllPhEDExNodeNames', None)] =====
===== Test::Success::CachedCRICService works as expected with Total/Hits/Misses == (12/9/3) =====
===== Test::Success::with accumulated Cache Stats:: (Hits/Misses) == (363/21) =====
```
But The new caching **also** mitigate flooding of ***CRIC*** debugging log from **WMCore** that we have to temporary turn-on-and-off using context manager: `with tempSetLogLevel(logger=self.logger, level=logging.ERROR):` throughout the codebase every time we call ***CRIC***-related functions at ***TaskWorker***.

**Comment by sinonkt** [comment]
**NOTES**: regarding https://github.com/dmwm/CRABServer/pull/8937#issuecomment-2666887239 extensive changes than we expected.
Please🥹, let me try explaining things here with my limited experience but a strong willingness to embrace clean code discipline.
### Problem Definition:
Throughout, **TaskWorker** code base, every time we wish to fetch **CRIC**-related sites info in any **TaskAction**. We ***instantiate*** **CRIC(logger=self.logger, configDict=configDict)** within either **envForCMSWEB** or **tempSetLogLevel** context manager, which leave us with kind of *boilerplate code* in many places as we can see in [1][2][3][4]. 
(P.S and also have high tendencies to be repeat the pattern elsewhere. e.g. in this issue there is **_checkSite**, **_expandSites** and **_checkASODestination** that extensively use multiple **CRIC** fns.)

[1]https://github.com/dmwm/CRABServer/blob/2283a7b9d4c342a78b16ec9ce4445abd9f236a9c/src/python/TaskWorker/Actions/DagmanCreator.py#L911-L915
[2]https://github.com/dmwm/CRABServer/blob/2283a7b9d4c342a78b16ec9ce4445abd9f236a9c/src/python/TaskWorker/Actions/DataDiscovery.py#L37-L41
[3]https://github.com/dmwm/CRABServer/blob/2283a7b9d4c342a78b16ec9ce4445abd9f236a9c/src/python/TaskWorker/Actions/UserDataDiscovery.py#L35-L38
[4]https://github.com/dmwm/CRABServer/blob/2283a7b9d4c342a78b16ec9ce4445abd9f236a9c/src/python/TaskWorker/Actions/MakeFakeFileSet.py#L19-L31
______________________
### Solution:
As you might know, what i'm trying to do is **Dependency Injection**, weak form of ***Inversion of Control (IoC)***,  like we did with **config** [***WMCore.Configuration***] on ***higher context manager*** (e.g. **Actions/Handler.py**). But not overdo it until becoming web frameworks like **Angular**, **Laravel** and **Nestjs**. 
1. Instantiate ***CachedCRICService*** at *Handler* and *PreDag* instead: such that we can easily inject ***CachedCRICService*** *instance* in any *TaskAction*. (PS. See also this commit https://github.com/dmwm/CRABServer/pull/8937/commits/11bd4b13361b2c1d7666e3d532d4c42f6c3d4ba2)
2. Generalize related Class's constructor signature: Since ***DataDiscovery*** Class is the one who use **CRIC** and is ***ParentClass*** of **DBSDataDiscovery**/**RucioDataDiscovery**/**UserDataDiscovery** so refactoring a bit to more generic constructor is *necessity* also easier to pass new **positional args** or **keyword args** later. (PS. As i did here https://github.com/dmwm/CRABServer/pull/8937/commits/3a5962276f424dcea68547b92b135c7b4abf9005)

______________________
### Clean Code Principles that we embrace/emphasize here:
1. ***Boy Scout Rule***: Leave the campground cleaner than you found it.🥹
2. **Use Dependency Injection**: I think in this issue it leave us (Future me and CRAB folks) with good practice/pattern to follows.
3. **Don't repeat ourself (DRY)**: reduce boilerplate/redundant code.
🥹 I'm by no means an expert at this. used to have discipline once in a while but wishes to be disciplined Boy Scout someday!
(See also in this gist [Summary of 'Clean code' by Robert C. Martin](https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29))

**Comment by sinonkt** [comment]
In response to Stefano's review, I've splitted this PR https://github.com/dmwm/CRABServer/issues/8938 into 2 stages as following.
- [x] #8943, tested on ***test12***, See [pipeline result here](https://gitlab.cern.ch/crab3/CRABServer/-/pipelines/10883923).
- [x] #8944 tested on ***test12***, See [pipeline result here](https://gitlab.cern.ch/crab3/CRABServer/-/pipelines/10884582).

**Comment by sinonkt** [comment]
In response to Stefano's review, I've split this PR https://github.com/dmwm/CRABServer/issues/8938 into 2 stages as following.
- [x] #8943, tested on ***test12***, See [pipeline result here](https://gitlab.cern.ch/crab3/CRABServer/-/pipelines/10883923).
- [x] #8944 tested on ***test12***, See [pipeline result here](https://gitlab.cern.ch/crab3/CRABServer/-/pipelines/10884582).
