### ISSUE TITLE
implement Publication with Rucio-based ASO

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7480]
replaces https://github.com/dmwm/CRABServer/issues/7223

Design of how we will do it is in https://github.com/dmwm/CRABServer/wiki/ASO-via-Rucio

From that the following action list follows

- [x] modify [Oracle/Create.py](https://github.com/dmwm/CRABServer/blob/master/src/python/Databases/FileTransfersDB/Oracle/Create.py) and [updateOracle.sql](https://github.com/dmwm/CRABServer/blob/master/etc/updateOracle.sql) to allow NULL values on deprecated-and-soon-to-be-removed `tm_rest_uri` and `tm_rest_host` and add new columns `tm_dbs_blockname`, `tm_block_complete` #7481
- [x] apply `updateOracle.sql` to all current DB's
   - [x] dev
   - [x] devtwo
   - [x] devthree
   - [x] preprod
   - [x] prod
   - [x] stefano
   - dciangot - can't change this, password expired
- [x] modify [RESTFileUserTransfer](https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTFileUserTransfers.py) to accept queries w/o the old `tm_rest_..` values . Now in [v3.221205](https://github.com/dmwm/CRABServer/releases/tag/v3.221205)
   - [x] validate in dev and preprod  #7505 
   - [x] deploy on all instances including  prod 
   - [x] modify `PostJob` not to write `tm_rest_*` anymore  #7507 . Validated in #7508
- [x] modify [RESTFileUserTransfer](https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTFileUserTransfers.py) to accept queries with new arg:  https://github.com/dmwm/CRABServer/commit/8819644578d4338a0b26874682dbfbc74a38d0cd in https://github.com/belforte/CRABServer/tree/add-support-for-dbs_blockname-_block_complete-in-REST
   - [x] validate-  OK in https://github.com/dmwm/CRABServer/issues/7520
- [x] modify `RESTFileTransfer.py` and [Oracle/FileTransfers/FileTransfers.py](https://github.com/dmwm/CRABServer/blob/master/src/python/Databases/FileTransfersDB/Oracle/FileTransfers
/FileTransfers.py) to support new columns so that `updatePublication` method accepts the new arguments
   - [x] vailidate -  OK in https://github.com/dmwm/CRABServer/issues/7520
- [x] once  modified `PostJob.py` has been in use for more than a month:
   - [x] verify that nothing writes or read to `tm_rest_*`
   - [x] remove them everywhere in the code #7795 #7796
   - [ ] remove old colums from DB
 
All code needed for above tasks is in https://github.com/dmwm/CRABServer/pull/7523
That results in a CRAB REST + TW deployment good enough to be used
as basis for implementing new code in RUCIO_Transfers.py and Publisher.py 

- [x] modity `RT.py` to fill properly  `tm_dbs_blockname` and `tm_block_complete` via nuw API `updatgeRucioInfo` - moved to issue https://github.com/dmwm/CRABServer/issues/7524
- [x] modify Publisher #7770

**Comment by novicecpp** [comment]
You can use this task to test 
- Task: https://cmsweb-test12.cern.ch/crabserver/ui/task/230712_052247:tseethon_crab_rucio_transfers_publication_test12_20230712_072245
- Rule: https://cms-rucio-webui.cern.ch/rule?rule_id=7a43c2054ec6431f9d32a25885824605
- Publish container: https://cms-rucio-webui.cern.ch/did?scope=user.tseethon&name=/GenericTTbar/tseethon-ruciotransfer-1689139365-94ba0e06145abd65ccb1d21786dc7e1d/USER

Or you can submit any HC-1kj (with Rucio transfer) task to test12. It is always on because I use it to test my scripts with user's tasks.

**Comment by belforte** [comment]
Perfect ! Thanks Wa

**Comment by belforte** [comment]
Adapting Publisher is not a few-hours work. Let me move to a neater ad hoc issue #7770

**Comment by belforte** [comment]
with https://github.com/dmwm/CRABServer/pull/7839 there is now in Master a version which runs and works in the few tasks I tested. I am going to tag and build to make sure that deploying as a container also works.

There is cleanup to be done and code duplication to remove, and issues will surface when testing more. But this can be considered done now.

**Comment by belforte** [comment]
the only item left here is
 * remove old colums from DB
better move that to a new issue, since it is simply a matter of making sure that new code is deployed everywhere
