### ISSUE TITLE
GOALS for 2023

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7635]
High Level goals which we set for ourselves for this year.
Updated on Sept 14, 2023

**goals we expect we will achieve**:

- [x] Install via piypi #7560   -  moved to 2024 #7876
- [x] Crab locks data before running #7592
- [x] Improved recovery task #7595  - moved to 2024 #7876
- [x] Support for PPC/Arm #7208
- [x] Full support for stage out via Rucio #7632 #7524 #7480 #7423 #7404 #7878 and all [issues referring ruci](https://github.com/dmwm/CRABServer/issues?q=is%3Aissue+is%3Aopen+label%3ARUCIO) in general
- [x] Report corrupted file replicas #7548
- [x] support for user file/dataset invalidation in phys03 https://github.com/dmwm/CRABClient/issues/5204
- [x] new `copycat` functionality for our testing and use in automatic recovery #7877  - moved to 2024 #7876

**Comment by belforte** [comment]
assing TOP priority since this list is something to keep in our minds

**Comment by belforte** [comment]
@novicecpp @mapellidario 
I have moved to #7876 what was still left and would like to close this now.
I will wait for your comments before doing it

**Comment by novicecpp** [comment]
Thanks for taking care.
Feel free to close it.
