### ISSUE TITLE
add REST API to list tasks by tm_ddm_reqid

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7646]
after the change in container name for tape recall requests in https://github.com/dmwm/CRABServer/pull/7641
we need a way to find which task is waiting on which rule, so that we can still build the table in https://github.com/dmwm/CRABServer/blob/master/scripts/Utils/CheckTapeRecall.py

- [x] add new API to REST - #7655
- [x] need also new SQL query - #7655 
- [x] modify CheckTapeRecall to use it - #7662 #7663 #7665 #7664
